### ISSUE TITLE
Multiple accordions are not working at once

### ISSUE THREAD

**Issue by bdalomgir** [backdrop-contrib/paragraphs_jquery_ui_accordion#7] opened 2022-10-11 11:19 UTC
I was trying to use multiple paragraphs jquery UI accordion in a site, but its not working. Every time first one is working but not the others. 
**Steps to reproduce:**

1. Create a paragraph type called **Accordion one** with two field 
    - Accordion Title
    - Accordion body
2. Create another paragraph type called **Accordion two** with another two field
    -  Title
    - Body
3. You can edit any content type, go to the manage fields(`/admin/structure/types/manage/page/fields`), and create two-paragraph reference fields.
    - Accordion one refers to the **Accordion one(paragraph type)**
    - Accordion two refers to the **Accordion two(paragraph type)**
4. Then go to the manage display(`/admin/structure/types/manage/accordion/display/default`) and make these two field **Format** as **Paragraphs jQuery UI Accordion** and configured these fields.
5. Create content(/node/add/page) and add some accordion in **Accordion one** and **Accordion two** fields.
6. Now you can see the **Accordion one** is working perfectly and **Accordion two** is not.

**Comment by alanmels** [comment] 2022-10-11 17:12
@bdalomgir, thanks for reporting this. Please note the module had been ported as is, so probably the issue is inherited from Drupal 7 version. Please try to make two patches given on https://www.drupal.org/project/paragraphs_jquery_ui_accordion/issues/3139221 working and let me know if it did as I really don't have time to troubleshoot this at the moment.

**Comment by bdalomgir** [comment] 2022-10-13 11:45
@alanmels Thanks for your suggestions. I tried to fix this from backend instead of JS. Here is the PR - https://github.com/backdrop-contrib/paragraphs_jquery_ui_accordion/pull/8 
Please have a look.

**Comment by alanmels** [comment] 2022-10-13 16:34
@bdalomgir, thanks for the PR, it has been tested and merged with dev.

**Closed as completed by alanmels** 2022-10-13 16:34 UTC

**Comment by stpaultim** [comment] 2022-10-14 04:24
Thanks @bdalomgir !!!!!
